# The task layer: the single implementation site for every repeatable piece of
# automation in this repository. Local development, git hooks
# (.pre-commit-config.yaml) and CI (.github/workflows/) are all just callers.
# Rules: no version numbers here (reference the SSOT of the layer below); no
# bashisms or duplicated arguments in recipes — each tool's parameters live in
# that tool's own config file.

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

export RUSTDOCFLAGS := "-D warnings"

# List all commands (just --list is living documentation)
default:
    @just --list

# Manual hook install for non-Nix shells — inside the devShell this happens
# automatically on entry (git cannot ship hooks with a clone)
setup:
    prek install --hook-type pre-commit --hook-type commit-msg

# In CI the pre-commit framework fails the job if files were modified by this
# (see the quality-gate job), so the check-mode twin is only exercised there.

# Format Rust (rustfmt) and markdown (dprint; config: dprint.json) — write mode
fmt:
    cargo fmt --all
    dprint fmt

# The two ignored shellcheck codes are style hints from the dist-generated
# release.yml, which we must not hand-edit (drift check); accepted policy.
# No path argument: actionlint discovers .github/workflows/ itself, because
# the Windows shell (PowerShell) does not expand globs for native commands.

# Static checks: rustfmt --check, dprint check (markdown), clippy (-D warnings), actionlint on workflow YAML
lint:
    cargo fmt --all -- --check
    dprint check
    cargo clippy --workspace --all-targets -- -D warnings
    actionlint -ignore 'SC2086' -ignore 'SC2129'

# Tests: nextest (process isolation) + doctests (README/rustdoc examples are compiled too)
test:
    cargo nextest run --workspace --all-targets
    cargo test --doc --workspace

# Build docs (rustdoc warnings are errors; RUSTDOCFLAGS injected at the top of this file)
doc:
    cargo doc --no-deps --workspace

# Dependency policy: advisories / licenses / duplicate versions / sources (see deny.toml).
# The two -D lints are the staleness fuses: an advisory ignore or per-crate
# license exception whose crate has left the tree fails CI instead of rotting.
deny:
    cargo deny check -D advisory-not-detected -D license-exception-not-encountered

# .github/workflows/release.yml is generated by `dist generate` — never
# hand-edit it; this recipe is the drift check (also a CI job).

# Drift check: fail if generated release.yml diverges from dist-workspace.toml
dist-check:
    dist generate --mode ci --check

# Snapshot review: approve diffs one by one; CI is read-only and never auto-accepts
snapshot-review:
    cargo insta review

# Run eval set v1 against a live provider (default kimi): full set, score file at target/eval/latest.json
eval:
    cargo run -q -p cadmus -- eval

# Cross-build the inline-spike harness for the Windows Terminal matrix leg
# (ADR-0018). Output: target/x86_64-pc-windows-gnu/release/examples/inline_spike.exe
# (self-contained: system DLLs only). One-time prerequisite: `rustup target
# add x86_64-pc-windows-gnu` — the flake toolchain intentionally has no
# windows target (the SSOT stays lean), so this runs on the user-profile
# rustup while rust-toolchain.toml still pins the channel. The pthreads -L
# path goes through nix eval because the mingw stdenv does not wire
# windows.pthreads into the linker search path (libpthread.a otherwise
# missing at link time).
spike-windows:
    #!/usr/bin/env sh
    set -eu
    PTHREADS_LIB="$(nix eval --raw nixpkgs#pkgsCross.mingwW64.windows.pthreads.outPath)/lib"
    nix shell nixpkgs#pkgsCross.mingwW64.stdenv.cc -c env \
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc \
        RUSTFLAGS="-L $PTHREADS_LIB" \
        cargo build -p cadmus-tui --example inline_spike --release --target x86_64-pc-windows-gnu

# The tmux leg of the inline-shell visual matrix (ADR-0018): drives the
# inline_spike harness through scripted resize gestures in a real terminal
# and asserts on capture-pane scrapes — band glued to the bottom across
# height grow/shrink and width shrink, the grow refill firing exactly once
# (the `inserts` counter gains one over the turn count), and zero band
# images anywhere in the frozen final buffer. This is the agent-runnable
# visual check: vt100 pins the mechanism, this leg judges compositing on a
# real top-anchoring terminal; Windows Terminal stays with spike-windows.
# Captures land in target/inline-spike/tmux/ for review. Requires tmux.
spike-tmux:
    #!/usr/bin/env sh
    set -eu
    cargo build -p cadmus-tui --example inline_spike
    out=target/inline-spike/tmux
    mkdir -p "$out"
    tmux kill-session -t spike 2>/dev/null || true
    trap 'tmux kill-session -t spike 2>/dev/null || true' EXIT
    tmux new-session -d -s spike -x 100 -y 24 "$PWD/target/debug/examples/inline_spike"
    tmux set-option -t spike remain-on-exit on
    sleep 4
    tmux capture-pane -t spike -p > "$out/1-baseline-100x24.txt"
    before=$(tmux capture-pane -t spike -p | grep -o 'turns [0-9]* · inserts [0-9]*' | grep -o '[0-9]*' | paste -sd' ' -)
    tmux resize-window -t spike -y 36 && sleep 1
    tmux capture-pane -t spike -p > "$out/2-grow-100x36.txt"
    after=$(tmux capture-pane -t spike -p | grep -o 'turns [0-9]* · inserts [0-9]*' | grep -o '[0-9]*' | paste -sd' ' -)
    tmux resize-window -t spike -y 20 && sleep 1
    tmux capture-pane -t spike -p > "$out/3-shrink-100x20.txt"
    tmux resize-window -t spike -x 60 && sleep 1
    tmux capture-pane -t spike -p > "$out/4-width-shrink-60x20.txt"
    for f in "$out"/2-*.txt "$out"/3-*.txt "$out"/4-*.txt; do
        tail -8 "$f" | grep -q 'turns [0-9]' || { echo "FAIL: band not glued to the bottom in $f"; exit 1; }
        # No band-signature line above the band rect on screen: the ghost
        # class (a vacated band image polluting the visible transcript).
        if head -n -8 "$f" | grep -q 'inline_spike — c · g · s · q\|turns [0-9]'; then
            echo "FAIL: band ghost above the band rect in $f"
            head -n -8 "$f" | grep -n 'inline_spike — c · g · s · q\|turns [0-9]'
            exit 1
        fi
    done
    set -- $before; tb=$1; ib=$2
    set -- $after;  ta=$1; ia=$2
    [ $((ia - ta)) -eq $((ib - tb + 1)) ] || { echo "FAIL: grow refill did not fire exactly once ($before -> $after)"; exit 1; }
    tmux send-keys -t spike q && sleep 1
    tmux capture-pane -t spike -p -S - > "$out/5-final-buffer.txt"
    # Report-only: tmux archives the on-screen band image into its own
    # scrollback at each resize gesture (terminal-side, the shell cannot
    # reach it) — one stale pair per gesture is expected here; growth
    # beyond the gesture count is the shell's ghost class and the captures
    # above fail on it first.
    grep -n 'inline_spike — c · g · s · q\|turns [0-9]' "$out/5-final-buffer.txt" || true
    echo "spike-tmux ok: band glued across grow/shrink/width-shrink, refill fired once, no on-screen ghosts"

# Smoke check for agent-facing docs: SKILL.md frontmatter, size budgets, and
# pointer integrity (AGENTS.md / CLAUDE.md / .claude/skills). Std-only Rust in
# crates/xtask; runs on every platform `just ci` runs on.
agent-check:
    cargo run -q -p xtask -- agent-check

# Architecture test: forbidden dependency edges + version SSOT + the
# serialization boundary (ADR-0002/0005). Std-only Rust in crates/xtask.
arch-test:
    cargo run -q -p xtask -- arch-test

# Bump rust-toolchain.toml's channel to the latest stable release. The weekly
# toolchain-update workflow wraps this in a validated PR; requires curl.
toolchain-bump:
    cargo run -q -p xtask -- bump-toolchain

# Secret scan of a PR's diff (added lines): token / private-key / .env shapes,
# hard fail. The pr-guard.yml workflow is the CI caller (needs gh + GH_TOKEN);
# `pr-guard --staged` is the local pre-commit half.
pr-guard pr="":
    cargo run -q -p xtask -- pr-guard {{pr}}

# The local full quality gate ≡ CI (modulo matrix dimensions); run before committing
ci: lint test doc deny agent-check arch-test
    @echo "just ci: all green ✅"

# Add an internal crate (unpublished by default; rules in CONTRIBUTING.md "Adding a crate")
new-crate name:
    cargo run -q -p xtask -- new-crate {{name}}
